synonyms:
  - [ ".net", "c#", "csharp", "dotnet", "net" ]
  - [ "esql", "es|ql" ]
  - [ "motlp", "managed otlp" ]
  - [ "s3", "aws s3", "amazon s3" ]
  - [ "es", "elasticsearch" ]
  - [ "elastic learned sparse encoder", "elser" ]
  - [ "ccs", "cross cluster search", "cross-cluster search", "spaghetti" ]
  - [ "cps", "cross project search", "cross-project search" ]
  - [ "apm", "application performance monitoring" ]
  - [ "ecctl", "elastic cloud control" ]
  - [ "opentelemetry", "otel" ]
  - [ "elastic distributions of opentelemetry", "edot" ]
  - [ "eck", "elastic cloud on kubernetes" ]
  - [ "ece", "elastic cloud enterprise" ]
  - [ "elv2", "elastic license v2" ]
  - [ "kql", "kibana query language" ]
  - [ "ccr", "cross-cluster replication", "cross cluster replication" ]
  - [ "esaas", "elastic stack as a service" ]
  - [ "knn", "k-nearest neighbors" ]
  - [ "ech", "elastic cloud hosted", "ess" ]
  - [ "elasticsearch service", "elastic cloud" ]
  - [ "aws", "amazon" ]
  - [ "gcp", "google cloud platform" ]
  - [ "ilm", "index lifecycle management" ]
  - [ "javascript", "js", "node", "nodejs", "node.js" ]
  - [ "edot", "elastic distribution of opentelemetry" ]
  - [ "k8s", "kubernetes" ]
  - [ "ecs", "elastic common schema" ]
  - [ "ml", "machine learning" ]
  - [ "eis", "elastic inference service" ]
  - [ "traffic filter", "network security" ]