synonyms:
  - [ ".net", ".NET", "c#", "csharp", "dotnet", "net", "NET", "DOTNET" ]
  - [ "esql", "es|ql" ]
  - [ "motlp", "managed otlp", "Managed OTLP" ]
  - [ "s3", "aws s3", "amazon s3" ]
  - [ "es", "elasticsearch" ]
  - [ "Elastic Learned Sparse EncodeR", "elser" ]
  - [ "ccs", "cross cluster search", "cross-cluster search", "spaghetti" ]
  - [ "apm", "application performance monitoring" ]
  - [ "ecctl", "Elastic Cloud Control" ]
  - [ "opentelemetry", "otel" ]
  - [ "eck", "Elastic Cloud on Kubernetes" ]
  - [ "ece", "Elastic Cloud Enterprise" ]
  - [ "ELv2", "Elastic License v2" ]
  - [ "kql", "Kibana Query Language" ]
  - [ "ccr", "cross-cluster replication", "cross cluster replication" ]
  - [ "ESaaS", "Elastic Stack as a service" ]
  - [ "knn", "k-Nearest Neighbors" ]
  - [ "ech", "Elastic Cloud Hosted", "ess" ]
  - [ "aws", "amazon" ]
  - [ "ilm", "index lifecycle management" ]
  - [ "javascript", "js", "node", "nodejs", "node.js" ]
  - [ "edot", "elastic distribution of opentelemetry" ]
  - [ "k8s", "kubernetes" ]