name: Deploy API Lambda

on:
  workflow_call: 
    inputs: 
      environment:
        required: true
        type: string
        description: edge, staging or prod
      ref:
        required: false
        type: string
        default: ${{ github.ref }}
    
permissions: 
  contents: read

jobs:
  build:
    permissions: 
      contents: read
    uses: ./.github/workflows/build-api-lambda.yml
    with: 
      ref: ${{ inputs.ref }}
  
  deploy:
    concurrency: ${{ github.workflow }}-${{ inputs.environment }}
    permissions: 
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment: docs-api-${{ inputs.environment }}
    env:
      ZIP_FILE: api-lambda.zip
    steps:
      - uses: actions/checkout@v5
          
      - name: Download bootstrap binary
        uses: actions/download-artifact@v4
        with:
          name: api-lambda-binary # Defined in build-api-lambda.yml

      - name: Create zip
        run: |
          zip -j "${ZIP_FILE}" ./bootstrap

      - uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          role-to-assume: arn:aws:iam::197730964718:role/elastic-docs-v3-api-deployer-${{ inputs.environment }}
          aws-region: us-east-1

      - name: Upload Lambda function
        run: |
          aws lambda update-function-code \
            --function-name "elastic-docs-v3-${ENVIRONMENT}-api" \
            --zip-file "fileb://${ZIP_FILE}"
        env:
          ENVIRONMENT: ${{ inputs.environment }}
